title: Fayette Lab
description: My Personal Blog.
author: Fayette Zhang
github: https://github.com/fayettecc/
about: I'm an undergraduate of the University of Rochester.
google_analytics: UA-222725512-1

enableTags: false
tagarray: []

collections:

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/profile.php?id=100012793803505"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/hongzhang2002/"
    - icon: fa-github
      link: "https://github.com/fayettecc/"

share:
  twitter_username: github.io

urls:
    - text: About Me
      url: /about/

url: "https://fayette.top/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
